apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: wordpress-mariadb-helm
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  WORDPRESS_DB_HOST: {{ printf "%s-mariadb:3306" .Release.Name | quote }}
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME', 'https://{{ required "satusky.domainName is required" .Values.satusky.domainName }}');
    define('WP_SITEURL', 'https://{{ required "satusky.domainName is required" .Values.satusky.domainName }}');
    define('FORCE_SSL_ADMIN', true);
