apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: wordpress-mariadb-helm
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ required "runtime databasePassword is required" (index .Values.satusky.credentials "databasePassword") | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "runtime databaseRootPassword is required" (index .Values.satusky.credentials "databaseRootPassword") | quote }}
