# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: 1ctl
version: 2

builds:
  - id: 1ctl-linux
    main: ./cmd/1ctl/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 1ctl/internal/version.Version={{.Version}}
      - -X 1ctl/internal/version.CommitHash={{.Commit}}
      - -X 1ctl/internal/version.BuildDate={{.Date}}

  - id: 1ctl-windows-darwin
    main: ./cmd/1ctl/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -X 1ctl/internal/version.Version={{.Version}}
      - -X 1ctl/internal/version.CommitHash={{.Commit}}
      - -X 1ctl/internal/version.BuildDate={{.Date}}

archives:
  - name_template: "1ctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files: [a-workaround-to-include-only-the-binary*]
    wrap_in_directory: false

source:
  enabled: true
  name_template: "1ctl-{{ .Version }}-source"

checksum:
  name_template: "1ctl-{{ .Version }}-checksums.sha256"

release:
  github:
    owner: satuskycloud
    name: 1ctl

changelog:
  disable: false
