// Code generated by tygo. DO NOT EDIT.

//////////
// source: admin.go

export interface DeploymentAdoptionRequest {
  reason: string;
  expected_uid: string;
  expected_resource_version: string;
  expected_generation: number /* int64 */;
}
export interface DeploymentAdoptionResult {
  deployment_id: string;
  namespace: string;
  app_label: string;
  cluster_id: string;
  live_uid: string;
  live_resource_version: string;
  desired_generation: number /* int64 */;
  observed_generation: number /* int64 */;
  reconciliation_state: string;
  reconciliation_managed: boolean;
  field_manager: string;
  force: boolean;
  already_managed: boolean;
  request_id: string;
}
export interface DeploymentRoutingAdoptionResult {
  deployment_id: string;
  namespace: string;
  name: string;
  live_uid: string;
  live_resource_version: string;
  live_generation: number /* int64 */;
  field_manager: string;
  force: boolean;
  already_managed: boolean;
  request_id: string;
}

//////////
// source: audit.go

export interface AuditLog {
  id: string /* UUID */;
  organization_id?: string /* UUID */;
  actor_id?: string /* UUID */;
  actor_email: string;
  actor_type: string;
  action: string;
  resource_type: string;
  resource_id?: string /* UUID */;
  resource_name: string;
  ip_address?: string;
  user_agent?: string;
  changes?: { [key: string]: unknown};
  metadata?: { [key: string]: unknown};
  created_at: string /* RFC3339 */;
}

//////////
// source: build.go

export interface BuildResponse {
  build_id: string;
  status: string;
}
export interface BuildStatusResponse {
  build_id: string;
  status: string;
  image_ref: string;
  image_arch: string;
  logs: string;
  error_message: string;
}
export const BuildBackendDefault = "";
export const BuildBackendDepot = "depot";
export interface BuildResult {
  ImageRef: string;
  ImageArch: string;
}

//////////
// source: cluster.go

export interface ZoneOption {
  value: string;
  label: string;
  cluster_id: string;
}
export interface ClusterInfo {
  id: string;
  name: string;
  display_name: string;
  region: string;
  zone: string;
  endpoint: string;
  priority: number /* int */;
  is_default: boolean;
  enabled: boolean;
  healthy: boolean;
}

//////////
// source: credits.go

export interface TierLimits {
  cpu: string;
  memory: string;
  pods: number /* int32 */;
  pvcs: number /* int32 */;
}
export interface TierInfo {
  current_tier: string;
  highest_tier: string;
  current_limits: TierLimits;
  next_tier?: string;
  next_tier_limits?: TierLimits;
  credits_to_next_tier: number /* float64 */;
  can_upgrade: boolean;
}
export interface CreditBalance {
  organization_id: string /* UUID */;
  balance: number /* float64 */;
  currency: string;
  updated_at: string /* RFC3339 */;
  tier?: TierInfo;
}
export interface CreditTransaction {
  transaction_id: string /* UUID */;
  organization_id: string /* UUID */;
  amount: number /* float64 */;
  transaction_type: string;
  description: string;
  created_at: string /* RFC3339 */;
}
export interface MachineUsage {
  usage_id: string /* UUID */;
  machine_id: string /* UUID */;
  machine_name: string;
  organization_id: string /* UUID */;
  hours_used: number /* float64 */;
  cost: number /* float64 */;
  status: string;
  start_time: string /* RFC3339 */;
  end_time?: string /* RFC3339 */;
}
export interface TopupRequest {
  amount: number /* float64 */;
  currency?: string;
}
export interface TopupResponse {
  session_id: string;
  payment_url: string;
  amount: number /* float64 */;
  status: string;
}
export interface Invoice {
  invoice_id: string /* UUID */;
  invoice_number: string;
  organization_id: string /* UUID */;
  amount: number /* float64 */;
  status: string;
  period_start: string /* RFC3339 */;
  period_end: string /* RFC3339 */;
  due_date?: string /* RFC3339 */;
  paid_at?: string /* RFC3339 */;
  created_at: string /* RFC3339 */;
}
export interface InvoiceSummary {
  total_invoices: number /* int */;
  total_amount: number /* float64 */;
  paid_amount: number /* float64 */;
  pending_amount: number /* float64 */;
  overdue_amount: number /* float64 */;
}
export interface GenerateInvoiceRequest {
  start_date: string /* RFC3339 */;
  end_date: string /* RFC3339 */;
}

//////////
// source: deployment_intent.go

export interface DeploymentIntent {
  deployment: Deployment;
  environment?: KeyValuePair[];
  config?: DeploymentDesiredStateConfig;
  volumes?: DeploymentIntentVolume[];
  service?: DeploymentIntentService;
  public_route?: DeploymentIntentPublicRoute;
}
export interface DeploymentDesiredStateConfig {
  startup_probe?: DeploymentProbe;
  readiness_probe?: DeploymentProbe;
  liveness_probe?: DeploymentProbe;
  required_secrets?: DeploymentRequiredSecret[];
}
export interface DeploymentRequiredSecret {
  key: string;
}
export interface DeploymentProbe {
  http_get?: DeploymentHTTPGetProbe;
  tcp_socket?: DeploymentTCPSocketProbe;
  exec?: DeploymentExecProbe;
  initial_delay_seconds?: number /* int32 */;
  timeout_seconds?: number /* int32 */;
  period_seconds?: number /* int32 */;
  success_threshold?: number /* int32 */;
  failure_threshold?: number /* int32 */;
}
export interface DeploymentHTTPGetProbe {
  path: string;
  port: number /* int32 */;
}
export interface DeploymentTCPSocketProbe {
  port: number /* int32 */;
}
export interface DeploymentExecProbe {
  command: string[];
}
export interface DeploymentIntentVolume {
  volume_name: string;
  claim_name: string;
  storage_class: string;
  storage_size: string;
  mount_path: string;
}
export interface DeploymentIntentService {
  name: string;
  port: number /* int32 */;
}
export interface DeploymentIntentPublicRoute {
  kind: string;
}
export interface DeploymentIntentAccepted {
  operation_id: string;
  deployment_id: string;
  namespace: string;
  app_label: string;
  generation: number /* int64 */;
  config_revision: number /* int64 */;
  config_sha256: string;
  state: string;
  status_url: string;
  missing_required_secrets?: string[];
}

//////////
// source: logs.go

export interface DeploymentLog {
  log_id: string /* UUID */;
  deployment_id: string /* UUID */;
  timestamp: string /* RFC3339 */;
  message: string;
  pod_name: string;
  container: string;
  level: string;
}
export interface DeploymentLogsMeta {
  source: string;
  degraded: boolean;
  fallback_reason?: string;
  fallback_source?: string;
  message: string;
}

//////////
// source: marketplace.go

export interface MarketplaceApp {
  marketplace_id: string /* UUID */;
  marketplace_name: string;
  description: string;
  image_url: string;
  category: string;
  metadata?: { [key: string]: unknown};
  supported_archs?: string[];
  package_release_id?: string /* UUID */;
  package_release?: MarketplacePackageRelease;
  deployable: boolean;
  coming_soon: boolean;
  deployment_count?: number /* int */;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface MarketplacePackageRelease {
  release_id: string /* UUID */;
  package_name: string;
  package_version: string;
  content_digest: string;
  manifest_metadata?: { [key: string]: unknown};
  certification_metadata?: { [key: string]: unknown};
  trusted: boolean;
  certified_at: string /* RFC3339 */;
  registered_at: string /* RFC3339 */;
  governance?: MarketplacePackageReleaseGovernance;
}
export interface MarketplacePackageReleaseGovernance {
  state: string;
  actor: string;
  reason: string;
  occurred_at: string /* RFC3339 */;
}
export interface MarketplaceDeployRequest {
  deployment_name: string;
  hostnames?: string[];
  replicas?: number /* int32 */;
  cpu_request?: string;
  memory_request?: string;
  storage_size?: string;
  values?: { [key: string]: unknown};
}
export interface MarketplaceDeployResponse {
  deployment_id: string /* UUID */;
  app_label: string;
  domain: string;
  status: string;
}

//////////
// source: marketplace_publisher.go

export interface MarketplacePackageArtifact {
  marketplace_id?: string;
  release_id: string;
  owner_organization_id?: string;
  archive_digest: string;
  visibility: string;
  created_at?: string /* RFC3339 */;
}

//////////
// source: models.go

export interface APIToken {
  token_id: string /* UUID */;
  user_id: string /* UUID */;
  name: string;
  token?: string;
  expires_at: string /* RFC3339 */;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface TokenValidate {
  valid: boolean;
  expires_at: string /* RFC3339 */;
  is_active: boolean;
  token_id?: string;
  user_id?: string;
  token?: string;
  user_email?: string;
  user_config_key?: string;
  organization_id?: string;
  organization_name?: string;
  namespace?: string;
  message?: string;
}
export interface MulticlusterConfig {
  enabled: boolean;
  mode: string;
  target_clusters?: string;
  backup_enabled?: boolean;
  backup_schedule?: string;
  backup_retention?: string;
  backup_priority_cluster?: number /* int */;
  failover_enabled?: boolean;
  restore_on_failover?: boolean;
}
export interface PDBConfig {
  enabled: boolean;
  type: string;
  min_available?: number /* int32 */;
  percent?: number /* int32 */;
}
export interface HPAConfig {
  enabled: boolean;
  min_replicas: number /* int32 */;
  max_replicas: number /* int32 */;
  cpu_target?: number /* int32 */;
  memory_target?: number /* int32 */;
  scale_up_stabilization?: number /* int32 */;
  scale_down_stabilization?: number /* int32 */;
  scale_up_max_pods?: number /* int32 */;
  scale_down_max_pods?: number /* int32 */;
}
export interface VPAConfig {
  enabled: boolean;
  update_mode: string;
  min_cpu?: string;
  max_cpu?: string;
  min_memory?: string;
  max_memory?: string;
}
export interface WaitFor {
  host: string;
  port: number /* int32 */;
}
export type DeploymentStrategyType = string;
export const StrategyRolling: DeploymentStrategyType = "rolling";
export const StrategyRecreate: DeploymentStrategyType = "recreate";
export interface RollingUpdateConfig {
  max_surge: string;
  max_unavailable: string;
}
export interface DeploymentStrategyConfig {
  type: DeploymentStrategyType;
  rolling?: RollingUpdateConfig;
}
export interface Deployment {
  deployment_id?: string /* UUID */;
  user_id: string /* UUID */;
  hostnames: string[];
  type: string;
  zone: string;
  region: string;
  ssd: string;
  gpu: string;
  namespace: string;
  replicas: number /* int32 */;
  image: string;
  app_label: string;
  port: number /* int32 */;
  cpu_request: string;
  cpu_limit?: string;
  memory_request: string;
  memory_limit: string;
  storage_size?: string;
  repo_url?: string;
  branch_name?: string;
  dockerfile_path?: string;
  env_enabled: boolean;
  secret_enabled: boolean;
  volume_enabled: boolean;
  status: string;
  environment: string;
  deployment_source?: string;
  marketplace_release_id?: string;
  source?: string;
  marketplace_app_id?: string;
  marketplace_app_name: string;
  multicluster_config?: MulticlusterConfig;
  pdb_config?: PDBConfig;
  hpa_config?: HPAConfig;
  vpa_config?: VPAConfig;
  deployment_strategy?: DeploymentStrategyConfig;
  wait_for?: WaitFor[];
  target_arch?: string;
  domain?: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface DeploymentDeletionLifecycle {
  state?: string;
  terminal: boolean;
  retryable?: boolean;
  code?: string;
  message?: string;
  errorCode?: string;
  errorMessage?: string;
}
export interface DeploymentDeletionOperation {
  deployment_id: string;
  namespace: string;
  app_label: string;
  operation: string;
  status: string;
  terminal: boolean;
  accepted_at?: string /* RFC3339 */;
  status_url?: string;
  poll_after_ms?: number /* int */;
  purge_retained: boolean;
  cleanup_scope?: string[];
  lifecycle: DeploymentDeletionLifecycle;
}
export interface CreateDeploymentResponse {
  deployment_id: string /* UUID */;
  ingress_id?: string /* UUID */;
  app_label: string;
  domain: string;
}
export interface DeploymentVersion {
  version_id: string;
  deployment_id: string;
  version_number: number /* int */;
  image: string;
  cpu: string;
  memory: string;
  replicas: number /* int */;
  deployed_at: string /* RFC3339 */;
  status: string;
}
export interface Secret {
  secret_id: string /* UUID */;
  deployment_id: string /* UUID */;
  namespace: string;
  key_values: KeyValuePair[];
  app_label: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface KeyValuePair {
  key: string;
  value: string;
}
export interface Ingress {
  ingress_id: string /* UUID */;
  deployment_id: string /* UUID */;
  namespace: string;
  service_id: string /* UUID */;
  app_label: string;
  port: number /* int32 */;
  domain_name: string;
  dns_config: DnsConfigType;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface IngressAlias {
  alias_id: string /* UUID */;
  ingress_id: string /* UUID */;
  domain_name: string;
  dns_config: DnsConfigType;
  domain_id?: string /* UUID */;
  is_redirect: boolean;
  redirect_to?: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface AttachDomainRequest {
  org_id: string /* UUID */;
  domain_name: string;
  with_www_redirect: boolean;
}
export interface DetachDomainRequest {
  org_id: string /* UUID */;
  domain_name: string;
}
export type DNSStatus = string;
export const DNSStatusResolved: DNSStatus = "resolved";
export const DNSStatusPropagating: DNSStatus = "propagating";
export const DNSStatusNotConfigured: DNSStatus = "not_configured";
export interface DNSStatusResponse {
  status: DNSStatus;
  domain: string;
  expected_ip?: string;
  resolved_ips?: string[];
  message?: string;
}
export type TLSStatus = string;
export const TLSStatusProvisioning: TLSStatus = "provisioning";
export const TLSStatusActive: TLSStatus = "active";
export const TLSStatusExpiringSoon: TLSStatus = "expiring_soon";
export const TLSStatusError: TLSStatus = "error";
export const TLSStatusNotApplicable: TLSStatus = "not_applicable";
export interface TLSStatusResponse {
  status: TLSStatus;
  expires_at?: string /* RFC3339 */;
  message?: string;
}
export interface DomainRouteStatus {
  attached: boolean;
  resource_kind?: string;
  resource_name?: string;
  namespace?: string;
  hostnames?: string[];
  message?: string;
}
export interface DomainReachabilityStatus {
  checked: boolean;
  reachable: boolean;
  status_code?: number /* int */;
  url?: string;
  message?: string;
}
export interface DomainStatusResponse {
  ingress_id: string /* UUID */;
  deployment_id: string /* UUID */;
  app_label: string;
  namespace: string;
  domain_name: string;
  dns_config: DnsConfigType;
  attached: boolean;
  route: DomainRouteStatus;
  dns: DNSStatusResponse;
  tls: TLSStatusResponse;
  reachability: DomainReachabilityStatus;
}
export interface Dependency {
  name: string;
  image: string;
  service?: Service;
  volume?: Volume;
}
export interface Volume {
  volume_id: string /* UUID */;
  deployment_id: string /* UUID */;
  volume_name: string;
  storage_class: string;
  storage_size: string;
  claim_name: string;
  mount_path: string;
  namespace: string;
  desired_attached: boolean;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface VolumePVCStatus {
  name: string;
  namespace: string;
  exists: boolean;
  phase?: string;
  storage_class?: string;
  capacity?: string;
  message?: string;
  last_observed_at?: string /* RFC3339 */;
}
export interface VolumeMountStatus {
  attached: boolean;
  mounted: boolean;
  path?: string;
  message?: string;
  last_observed_at?: string /* RFC3339 */;
}
export interface VolumeLifecycleStatus {
  volume: Volume;
  pvc: VolumePVCStatus;
  mount: VolumeMountStatus;
  destroy_policy: string;
}
export interface VolumeDestroyResult {
  volume_id: string /* UUID */;
  volume_name: string;
  claim_name: string;
  namespace: string;
  status: string;
  destroy_policy: string;
  message?: string;
}
export interface DeletionResult {
  deleted_deployments: string[];
  namespace: string;
  app_label: string;
  is_cnpg_deployment: boolean;
  volumes?: VolumeDestroyResult[];
}
export interface Service {
  service_id: string /* UUID */;
  deployment_id: string /* UUID */;
  namespace: string;
  service_name: string;
  port: number /* int32 */;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface Environment {
  environment_id: string /* UUID */;
  deployment_id: string /* UUID */;
  namespace: string;
  app_label: string;
  key_values: KeyValuePair[];
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface Organization {
  organization_id: string /* UUID */;
  organization_name: string;
  namespace?: string;
  description?: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface User {
  user_id: string /* UUID */;
  email: string;
  user_name: string;
  organization_ids: string[];
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface UserProfile {
  user_id: string;
  email: string;
  name: string;
  organization: string;
  role: string;
  created_at: string /* RFC3339 */;
}
export type DnsConfigType = string;
export const DnsConfigDefault: DnsConfigType = "default";
export const DnsConfigCustom: DnsConfigType = "custom";
export interface APIError {
  message: string;
  code: string;
  details: unknown;
  retryable?: boolean;
  remediation?: string[];
  request_id?: string;
}
export interface HTTPStatusError {
  StatusCode: number /* int */;
  Message: string;
  RetryAfter: number /* nanoseconds */;
  Code: string;
  Details: unknown;
  Retryable?: boolean;
  Remediation: string[];
  RequestID: string;
}
export const StatusPending = "pending";
export const StatusCreating = "creating";
export const StatusRunning = "running";
export const StatusFailed = "failed";
export const StatusCompleted = "completed";
export const StatusNotReady = "NotReady";
export const StatusRunningK8s = "Running";
export const StatusFailedK8s = "Failed";
export const StatusProgressing = "Progressing";
export const StatusUnknown = "Unknown";
export interface DeploymentStatus {
  status: string;
  message?: string;
  progress: number /* int */;
  replica_status?: string;
  readiness?: DeploymentReadiness;
}
export interface DeploymentReadiness {
  reconciliation: DeploymentReconciliationReadiness;
  workload: DeploymentWorkloadReadiness;
  application: DeploymentConditionReadiness;
  route: DeploymentConditionReadiness;
  dns: DeploymentConditionReadiness;
  public_reachability: DeploymentConditionReadiness;
}
export interface DeploymentReconciliationReadiness {
  state: string;
  generation: number /* int64 */;
  observed_generation: number /* int64 */;
}
export interface DeploymentWorkloadReadiness {
  state: string;
  desired_replicas: number /* int32 */;
  ready_replicas: number /* int32 */;
  available_replicas: number /* int32 */;
  updated_replicas: number /* int32 */;
}
export interface DeploymentConditionReadiness {
  basis: string;
  state: string;
}
export type DeploymentWaitMode = string;
export const DeploymentWaitModeApplication: DeploymentWaitMode = "application";
export const DeploymentWaitModeWorkload: DeploymentWaitMode = "workload";
export interface Machine {
  id: number /* int64 */;
  machine_id: string;
  machine_name: string;
  machine_types: string[];
  owner_id: string /* UUID */;
  is_verified: boolean;
  machine_region: string;
  machine_zone: string;
  ip_addr: string;
  talos_version: string;
  kubernetes_version: string;
  cpu_cores: number /* int */;
  memory_gb: number /* int */;
  storage_gb: number /* int */;
  gpu_count: number /* int */;
  gpu_type: string;
  bandwidth_gbps: number /* int */;
  brand: string;
  model: string;
  manufacturer: string;
  form_factor: string;
  monetized: boolean;
  status: string;
  last_health_check: string | null;
  recommended: boolean;
  resource_score: number | null;
  cpu_usage_percent: number | null;
  memory_usage_percent: number | null;
  storage_usage_percent: number | null;
  network_usage_gbps: number | null;
  network_metrics_type: string;
  connection_mode?: string;
  vm_state?: string;
  uptime_percent: number | null;
  response_time_ms: number | null;
  node_type: string;
  has_gpu: boolean;
  has_hdd: boolean;
  has_nvme: boolean;
  pricing_tier: string;
  hourly_cost: number /* float64 */;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
  cpu_arch: string;
  organization_id?: string;
}
export interface MachineIDs {
  machine_ids: string[];
}
export const CmdStart = "CMD_START";
export const CmdStop = "CMD_STOP";
export const CmdForceStop = "CMD_FORCE_STOP";
export const CmdReboot = "CMD_REBOOT";
export const CmdResize = "CMD_RESIZE";
export const CmdApplyConfig = "CMD_APPLY_TALOS_CONFIG";
export const CmdStreamConsole = "CMD_STREAM_CONSOLE";
export interface Domain {
  domain_id: string;
  name: string;
  status: string;
  ttl: number /* int */;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface DNSRecord {
  record_id: string;
  domain_id: string;
  type: string;
  name: string;
  data: string;
  priority?: number /* int */;
  port?: number /* int */;
  weight?: number /* int */;
  ttl: number /* int */;
  flags?: number /* int */;
  tag?: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface DomainPrice {
  amount: number /* float64 */;
  currency: string;
}
export interface DomainAvailabilityResult {
  domain: string;
  available: boolean;
  status: string;
  reason?: string;
  is_premium?: boolean;
  price?: DomainPrice;
  premium_price?: number /* float64 */;
}
export interface DomainSearchResult {
  domain: string;
  extension: string;
  available: boolean;
  status: string;
  price: number /* float64 */;
  currency: string;
  is_premium: boolean;
  period: number /* int */;
}
export interface NameserverStatus {
  verified: boolean;
  current_nameservers: string[];
  expected_nameservers: string[];
  message: string;
}
export interface DomainContactInfo {
  first_name: string;
  last_name: string;
  email: string;
  phone_country_code: string;
  phone_number: string;
  street: string;
  street_number: string;
  postal_code: string;
  city: string;
  state?: string;
  country: string;
  company_name?: string;
}
export interface DomainCreateRequest {
  name: string;
  ip_address?: string;
}
export interface DomainCheckRequest {
  domains: string[];
  with_price: boolean;
}
export interface DomainSearchRequest {
  domain_name: string;
  extensions?: string[];
  period?: number /* int */;
}
export interface DomainPurchaseRequest {
  domain: string;
  period?: number /* int */;
  contact: DomainContactInfo | null;
}
export interface DomainPurchaseIntentResponse {
  session_id: string;
  redirect_url: string;
  domain: string;
  price: number /* float64 */;
  currency: string;
  intent_id: string;
}
export interface DomainPurchaseIntentStatus {
  intent_id: string;
  domain: string;
  status: string;
}
export interface DNSRecordCreateRequest {
  type: string;
  name: string;
  data: string;
  priority?: number /* int */;
  port?: number /* int */;
  weight?: number /* int */;
  ttl?: number /* int */;
  flags?: number /* int */;
  tag?: string;
}
export interface DNSRecordUpdateRequest {
  type?: string;
  name?: string;
  data?: string;
  priority?: number /* int */;
  port?: number /* int */;
  weight?: number /* int */;
  ttl?: number /* int */;
  flags?: number /* int */;
  tag?: string;
}
export interface MachineUsageRecord {
  usage_id: string;
  deployment_id: string;
  machine_id: string;
  user_id: string;
  organization_id: string;
  start_time: string;
  end_time?: string;
  hourly_rate: number /* float64 */;
  status: string;
  is_billed: boolean;
  last_billed_at?: string;
  machine_ref_id?: number /* int64 */;
  created_at: string;
  updated_at: string;
}
export interface UsageCostResponse {
  usage_id: string;
  cost: number /* float64 */;
}
export interface PricingConfig {
  config_id: string;
  region: string;
  machine_type: string;
  sla_tier: string;
  base_hourly_rate: number /* float64 */;
  cpu_core_rate: number /* float64 */;
  memory_gb_rate: number /* float64 */;
  storage_gb_rate: number /* float64 */;
  gpu_rate: number /* float64 */;
  bandwidth_gbps_rate: number /* float64 */;
  created_at: string;
  updated_at: string;
}
export interface CostCalculationRequest {
  start_time: string;
  end_time: string;
}
export interface CostBreakdown {
  base_cost: number /* float64 */;
  cpu_cost: number /* float64 */;
  memory_cost: number /* float64 */;
  storage_cost: number /* float64 */;
  gpu_cost: number /* float64 */;
  bandwidth_cost: number /* float64 */;
}
export interface CostCalculationResponse {
  machine_id: string;
  machine_ref_id: number /* int64 */;
  start_time: string;
  end_time: string;
  total_cost: number /* float64 */;
  breakdown: CostBreakdown;
}
export interface AutoTopupSettings {
  settings_id: string;
  organization_id: string;
  enabled: boolean;
  threshold_amount: number /* float64 */;
  topup_amount: number /* float64 */;
  has_payment_method: boolean;
  payment_method_last4?: string;
  payment_method_brand?: string;
  last_topup_at?: string;
  created_at: string;
  updated_at: string;
}
export interface AutoTopupSettingsRequest {
  enabled: boolean;
  threshold_amount: number /* float64 */;
  topup_amount: number /* float64 */;
}
export interface NotificationPreferences {
  id: string;
  organization_id: string;
  email_enabled: boolean;
  in_app_enabled: boolean;
  webhook_enabled: boolean;
  webhook_url?: string;
  enabled_types: string[];
  quiet_hours_enabled: boolean;
  quiet_hours_timezone?: string;
  digest_enabled: boolean;
  digest_frequency?: string;
  low_balance_threshold_percent: number /* int */;
  low_balance_threshold_amount: number /* float64 */;
  alert_cooldown_hours: number /* int */;
}
export interface NotificationPreferencesRequest {
  email_enabled: boolean;
  in_app_enabled: boolean;
  webhook_enabled: boolean;
  webhook_url?: string;
  enabled_types?: string[];
  quiet_hours_enabled: boolean;
  quiet_hours_start?: string;
  quiet_hours_end?: string;
  quiet_hours_timezone?: string;
  digest_enabled: boolean;
  digest_frequency?: string;
  low_balance_threshold_percent: number /* int */;
  low_balance_threshold_amount: number /* float64 */;
  alert_cooldown_hours: number /* int */;
}
export interface SendCommandRequest {
  type: string;
  payload?: { [key: string]: unknown};
}
export interface SendCommandResponse {
  command_id: string;
  status: string;
}
export interface MachineLogFetchRequest {
  machine_id?: string;
  sources?: string[];
  follow?: boolean;
  tail_lines?: number /* int */;
  since?: string;
  filter?: string;
  components?: string[];
  include_prev_log?: boolean;
}
export interface MachineLogEntry {
  timestamp: string;
  source: string;
  stage: string;
  message: string;
  severity?: string;
  component?: string;
}
export interface MachineLogsResponse {
  machine_id: string;
  entries: MachineLogEntry[];
  count: number /* int */;
  stage: string;
  fetched_at: string;
}
export interface MachineEvent {
  id: string;
  type_url: string;
  actor_id?: string;
  node?: string;
  payload?: string;
}
export interface MachineEventsResponse {
  machine_id: string;
  events: MachineEvent[];
  count: number /* int */;
}

//////////
// source: notifications.go

export interface Notification {
  notification_id: string /* UUID */;
  organization_id: string /* UUID */;
  user_id?: string /* UUID */;
  type: string;
  channel: string;
  priority: string;
  status: string;
  subject: string;
  message: string;
  data?: { [key: string]: unknown};
  read_at?: string /* RFC3339 */;
  created_at: string /* RFC3339 */;
}
export interface UnreadCount {
  count: number /* int */;
}

//////////
// source: org.go

export interface TeamMember {
  organization_user_id: string /* UUID */;
  user_id: string /* UUID */;
  organization_id: string /* UUID */;
  user_email: string;
  user_name?: string;
  role: string;
  created_at: string /* RFC3339 */;
}
export interface CreateOrganizationRequest {
  organization_name: string;
  description?: string;
}
export interface AddTeamMemberRequest {
  email: string;
  role: string;
}
export interface UpdateTeamMemberRoleRequest {
  role: string;
}

//////////
// source: postgres.go

export type StorageEngine = string;
export const StorageEngineCNPG: StorageEngine = "cnpg";
export const StorageEngineValkey: StorageEngine = "valkey";
export interface ValkeyConfig {
  topology: string;
  machine_id?: string;
  append_only?: boolean;
  append_fsync: string;
  maxmemory_policy: string;
  maxmemory_percent: number /* int */;
  metrics_enabled?: boolean;
  chart_version: string;
  image_version: string;
  chart_digest_sha256?: string;
  users?: ValkeyUserConfig[];
}
export interface ValkeyUserConfig {
  username: string;
  access_preset: string;
  key_patterns?: string[];
  channel_patterns?: string[];
}
export interface StorageConfig {
  storage_id?: string /* UUID */;
  resource_id: string /* UUID */;
  resource_type: string;
  namespace: string;
  organization_id?: string /* UUID */;
  engine: StorageEngine;
  version: string;
  replicas: number /* int */;
  database_name?: string;
  cluster_name?: string;
  username?: string;
  port?: string;
  storage_size: string;
  storage_class: string;
  cpu_request: string;
  cpu_limit: string;
  memory_request: string;
  memory_limit: string;
  wal_storage_size?: string;
  wal_storage_class?: string;
  instances?: number /* int */;
  replication_mode?: string;
  persistence_enabled?: boolean;
  valkey?: ValkeyConfig;
  admin_ui_enabled?: boolean;
  labels?: { [key: string]: string};
  annotations?: { [key: string]: string};
  created_at?: string /* RFC3339 */;
  updated_at?: string /* RFC3339 */;
}
export interface PostgresCreateOptions {
  Name: string;
  Database: string;
  Username: string;
  Version: string;
  Instances: number /* int */;
  StorageSize: string;
  StorageClass: string;
  WALStorageSize: string;
  CPURequest: string;
  CPULimit: string;
  MemoryRequest: string;
  MemoryLimit: string;
}
export interface PostgresCredentials {
  username: string;
  password: string;
  host: string;
  port: string;
  dbname: string;
  uri: string;
  internal_host: string;
  internal_uri: string;
  external_host?: string;
  external_port?: string;
  external_uri?: string;
}
export interface PostgresStatus {
  status: string;
  cluster_phase: string;
  cluster_exists: boolean;
  ready_instances: number /* int */;
  total_instances: number /* int */;
  primary: string;
  pooler_ready: boolean;
  pooler_ready_replicas: number /* int */;
  pooler_desired_replicas: number /* int */;
  external_accessible: boolean;
}
export interface CNPGDatabaseUser {
  user_id: string /* UUID */;
  storage_id: string /* UUID */;
  username: string;
  secret_name: string;
  role_attributes: string[];
  comment?: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface CreateDatabaseUserRequest {
  username: string;
  role_attributes?: string[];
  comment?: string;
}
export interface CreateDatabaseUserResponse {
  data: CNPGDatabaseUser;
  password: string;
  ready: boolean;
  reconciliation_status?: string;
  readiness_message?: string;
}
export interface CNPGFirewallRule {
  rule_id: string /* UUID */;
  storage_id: string /* UUID */;
  description: string;
  cidr: string;
  enabled: boolean;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export interface CreateFirewallRuleRequest {
  description: string;
  cidr: string;
}
export interface UpdateFirewallRuleRequest {
  description?: string;
  cidr?: string;
  enabled?: boolean;
}
export interface StorageClassInfo {
  name: string;
  provisioner: string;
  is_default: boolean;
}

//////////
// source: token.go

export interface CLIToken {
  token_id: string /* UUID */;
  organization_user_id?: string /* UUID */;
  name: string;
  description?: string;
  token?: string;
  last_used_at?: string /* RFC3339 */;
  expires_at?: string /* RFC3339 */;
  is_active: boolean;
  created_at: string /* RFC3339 */;
}
export interface CreateTokenRequest {
  name: string;
  expires_in?: number /* int */;
}
export interface TokenStateRequest {
  enabled: boolean;
}
export interface DeleteTokenRequest {
  token_id: string;
}

//////////
// source: user.go

export interface CLIUserProfile {
  user_id: string;
  email: string;
  name?: string;
  organization?: string;
  role?: string;
  created_at: string /* RFC3339 */;
}
export interface UserPermission {
  permission_name: string;
  permission_description: string;
  resource_type: string;
  action: string;
}
export interface UpdateUserRequest {
  name?: string;
  email?: string;
}
export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}

//////////
// source: valkey.go

export const ValkeyVersion = "9.1.1";
export const ValkeyChartVersion = "0.11.0";
export interface ValkeyCreateOptions {
  Name: string;
  MachineID: string;
  Topology: string;
  Instances: number /* int */;
  Persistence: boolean;
  StorageSize: string;
  StorageClass: string;
  CPURequest: string;
  CPULimit: string;
  MemoryRequest: string;
  MemoryLimit: string;
  AppendOnly: boolean;
  AppendFsync: string;
  MaxmemoryPolicy: string;
  MaxmemoryPercent: number /* int */;
  MetricsEnabled: boolean;
}
export interface ValkeyStatus {
  status: string;
  workload_kind: string;
  ready_instances: number /* int */;
  desired_instances: number /* int */;
  primary: string;
  private_host: string;
  read_only_host?: string;
  metrics_enabled: boolean;
  persistence_enabled: boolean;
}
export interface ValkeyCredentials {
  username: string;
  password: string;
  host: string;
  port: string;
  uri: string;
  read_only_host?: string;
  read_only_uri?: string;
  tls: boolean;
}
export interface ValkeyCreateUserRequest {
  username: string;
  access_preset: string;
  key_patterns?: string[];
  channel_patterns?: string[];
}
export interface ValkeyUpdateUserRequest {
  access_preset?: string;
  key_patterns?: string[];
  channel_patterns?: string[];
}
export interface ValkeyCreatedUser {
  user: ValkeyUserConfig;
  password: string;
  notice?: string;
  restart_pending?: boolean;
}
export interface ValkeyRotatedCredential {
  username: string;
  password: string;
  notice?: string;
  restart_pending?: boolean;
}
export interface ValkeyLogs {
  lines: string[];
  pod: string;
}
