name: Check spelling

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main
    - feature/**

permissions:
  contents: read

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Check spelling
      uses: crate-ci/typos@320b5781474d4470a36b7f0626b131e99850e9d2 # v1.23.2
